// <auto-generated />
using System;
using BlazorEmployeeCRUD.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEmployeeCRUD.DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEmployeeCRUD.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 25,
                            DateOfBirth = new DateTime(1999, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Abc",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 24,
                            DateOfBirth = new DateTime(1999, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Mno",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 29,
                            DateOfBirth = new DateTime(1993, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Excecutive",
                            FullName = "Xyz",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 25,
                            DateOfBirth = new DateTime(1999, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Dfg",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Age = 25,
                            DateOfBirth = new DateTime(1991, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Qml",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Age = 28,
                            DateOfBirth = new DateTime(1993, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Manufacturing",
                            FullName = "Bju",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Age = 32,
                            DateOfBirth = new DateTime(1988, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Kgd",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Age = 25,
                            DateOfBirth = new DateTime(1990, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Cey",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Age = 26,
                            DateOfBirth = new DateTime(1998, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Excecutive",
                            FullName = "Ndw",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Age = 24,
                            DateOfBirth = new DateTime(2000, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Production",
                            FullName = "Mki",
                            PhoneNumber = "1234567890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
